spring:
  application:
    name: @project.artifactId@

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sea-ls/dripid-config.git
          username: my_temp_access_token
          password: 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
          search-paths: "{application}"

server:
  port: 8888