spring:
  application:
    name: @project.artifactId@

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sea-ls/dripid-config.git
          username: my_temp_access_token
          password: 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
          search-paths: "{application}"

server:
  port: 8888