server:
  port: 9090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/auth/realms/${keycloak.realm}

jwt:
  auth:
    converter:
      resource-id: pbpkce_client

keycloak:
  realm: dripId
  domain: localhost:9000
  adminClientId: admin-cli
  adminClientSecret: 3eymGxdPIUMDzEsKggCJRw2sbQZdOqvC
  client: pbpkce_client
  urls:
    auth: http://${keycloak.domain}/auth
