CREATE TABLE IF NOT EXISTS "users"(
    "id" BIGSERIAL PRIMARY KEY,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "username" VARCHAR(255),
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(255) NOT NULL
);