version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - auth-pgdata-volume:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local


  keycloak:
    image: keycloak/keycloak:24.0
    command: start-dev
    restart: always
    depends_on:
      - postgres
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    networks:
      - local

networks:
  local:

volumes:
  auth-pgdata-volume:
    name: docker_auth-pgdata