version: "3.9"
services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: keycloak_db
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /mnt/docker/keycloak/db:/var/lib/postgresql/data:rw
    ports:
      - 5431:5432
  kc:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      DB_URL: jdbc:postgresql://db:5432/keycloak_db
      DB_USER: my_admin
      DB_SCHEMA: public
      DB_PASSWORD: my_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9000:8080
    depends_on:
      - db