version: '3.9'

services:
  zipkinserver:
    image: openzipkin/zipkin:3
    deploy:
      resources:
        limits: *resources-low
      update_config: *update-config-30s
    logging: *default-logging
    secrets:
      - zipkin.properties
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=https://es01:9200
      - ES_SSL_NO_VERIFY=true
      - ES_CREDENTIALS_FILE=/run/secrets/zipkin.properties
      - JAVA_OPTS=-Xms32m -Xmx32m -XX:+ExitOnOutOfMemoryError -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000
    ports:
      - "9411:9411"
      - "5029:5000"
    healthcheck:
      disable: true

secrets:
  zipkin.properties:
    name: elk_zipkin.properties
    external: true

networks:
  default:
    name: dripid-network
    external: true


