name: Migration develop

on:
  workflow_dispatch:
    branches:
      - "develop"
  push:
    paths:
      - 'migrations/**'
env:
  CI_COMMIT_BRANCH: "develop"

jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: docker run -v ./migrations/delivery-service:/liquibase/changelog liquibase/liquibase update --url=jdbc:postgresql://212.233.73.223:5433/dripId --searchPath="./migrations/delivery-service" --changelog-file=master.xml --username=postgres --password=postgres
